# Generated by Django 6.0 on 2025-12-12 07:47

import django.core.validators
import django.db.models.deletion
import quiz_app.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=quiz_app.models.generate_session_code, help_text='4 цифры для подключения', max_length=4, unique=True, verbose_name='Код сессии')),
                ('state', models.CharField(choices=[('waiting', 'Ожидание игроков'), ('running', 'Игра идёт'), ('paused', 'На паузе'), ('finished', 'Завершена')], default='waiting', max_length=20, verbose_name='Состояние')),
                ('current_question', models.IntegerField(default=0, help_text='Индекс текущего вопроса (начиная с 0)', verbose_name='Текущий вопрос')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Время начала игры')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
            ],
            options={
                'verbose_name': 'Игровая сессия',
                'verbose_name_plural': 'Игровые сессии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('order', models.IntegerField(help_text='Порядок вопроса в квизе', verbose_name='Порядковый номер')),
                ('text', models.TextField(max_length=200, verbose_name='Текст вопроса')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный'), ('very_hard', 'Очень сложный'), ('fun', 'Шуточный')], default='medium', max_length=20, verbose_name='Сложность')),
                ('explanation', models.TextField(blank=True, help_text='Показывается после ответа', max_length=300, verbose_name='Объяснение')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='URL картинки')),
                ('generated_by_model', models.BooleanField(default=True, verbose_name='Сгенерирован LLM')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название квиза')),
                ('topic', models.CharField(help_text='Например: Советские фильмы, География России', max_length=200, verbose_name='Тема')),
                ('description', models.TextField(blank=True, help_text='Автогенерируется LLM или заполняется вручную', verbose_name='Описание')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='URL картинки темы')),
                ('question_count', models.IntegerField(default=0, verbose_name='Количество вопросов')),
                ('time_per_question', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(60)], verbose_name='Время на вопрос (сек)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Квиз',
                'verbose_name_plural': 'Квизы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя игрока')),
                ('score', models.IntegerField(default=0, verbose_name='Счёт')),
                ('current_streak', models.IntegerField(default=0, help_text='Количество правильных ответов подряд', verbose_name='Текущая серия')),
                ('max_streak', models.IntegerField(default=0, verbose_name='Максимальная серия')),
                ('connected', models.BooleanField(default=True, verbose_name='Подключён')),
                ('last_seen', models.DateTimeField(auto_now_add=True, help_text='Обновляется при каждом ping', verbose_name='Последняя активность')),
                ('is_host', models.BooleanField(default=False, verbose_name='Является ведущим')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Время подключения')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='quiz_app.gamesession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['-score'],
                'unique_together': {('session', 'name')},
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_sessions', to='quiz_app.player', verbose_name='Ведущий'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz_app.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_app.quiz', verbose_name='Квиз'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='quiz_app.quiz', verbose_name='Квиз'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken', models.FloatField(help_text='Сколько секунд потребовалось для ответа', verbose_name='Время ответа (сек)')),
                ('is_correct', models.BooleanField(verbose_name='Правильный ответ')),
                ('points_earned', models.IntegerField(verbose_name='Заработанные очки')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Время ответа')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.choice', verbose_name='Выбранный вариант')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz_app.player', verbose_name='Игрок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz_app.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['answered_at'],
                'unique_together': {('player', 'question')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('quiz', 'order')},
        ),
    ]
