# Generated by Django 6.0 on 2025-12-14 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=0, help_text='0 = использовать время из квиза. Можно задать индивидуальное время для сложных вопросов', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Время на вопрос (сек)'),
        ),
    ]
