# Generated by Django 6.0 on 2026-02-09 14:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_question_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_custom_settings',
            field=models.BooleanField(default=False, help_text='True если вопрос настроен вручную', verbose_name='Имеет индивидуальные настройки'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Текстовый'), ('image', 'С изображением'), ('audio', 'Аудио вопрос'), ('video', 'Видео вопрос')], default='text', max_length=20, verbose_name='Тип вопроса'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic_refinement',
            field=models.CharField(blank=True, help_text='Конкретизация темы для этого вопроса (например: Вторая мировая война)', max_length=200, verbose_name='Уточнение темы'),
        ),
        migrations.CreateModel(
            name='QuizDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Тема квиза')),
                ('num_questions', models.IntegerField(default=10, verbose_name='Количество вопросов')),
                ('base_difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный'), ('very_hard', 'Очень сложный'), ('fun', 'Шуточный')], default='medium', max_length=20, verbose_name='Базовая сложность')),
                ('base_time_limit', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)], verbose_name='Базовое время на вопрос (сек)')),
                ('base_question_type', models.CharField(choices=[('text', 'Текстовый'), ('image', 'С изображением'), ('audio', 'Аудио вопрос'), ('video', 'Видео вопрос')], default='text', max_length=20, verbose_name='Базовый тип вопроса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_generated', models.BooleanField(default=False, verbose_name='Сгенерирован')),
                ('generated_quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='quiz_app.quiz', verbose_name='Сгенерированный квиз')),
            ],
            options={
                'verbose_name': 'Черновик квиза',
                'verbose_name_plural': 'Черновики квизов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядковый номер вопроса')),
                ('use_custom_settings', models.BooleanField(default=False, verbose_name='Использовать индивидуальные настройки')),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный'), ('very_hard', 'Очень сложный'), ('fun', 'Шуточный')], max_length=20, verbose_name='Сложность')),
                ('time_limit', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)], verbose_name='Время на вопрос (сек)')),
                ('question_type', models.CharField(blank=True, choices=[('text', 'Текстовый'), ('image', 'С изображением'), ('audio', 'Аудио вопрос'), ('video', 'Видео вопрос')], max_length=20, verbose_name='Тип вопроса')),
                ('topic_refinement', models.CharField(blank=True, max_length=200, verbose_name='Уточнение темы')),
                ('is_generated', models.BooleanField(default=False, verbose_name='Сгенерирован')),
                ('generated_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configs', to='quiz_app.question', verbose_name='Сгенерированный вопрос')),
                ('quiz_draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_configs', to='quiz_app.quizdraft', verbose_name='Черновик квиза')),
            ],
            options={
                'verbose_name': 'Конфигурация вопроса',
                'verbose_name_plural': 'Конфигурации вопросов',
                'ordering': ['order'],
                'unique_together': {('quiz_draft', 'order')},
            },
        ),
    ]
